---
- name: Remover recursos do Azure
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Verificar se o grupo de recursos existe
      azure_rm_resourcegroup_info:
        name: myResourceGroup
      register: resource_group_check
      ignore_errors: yes

    - name: Remover a máquina virtual se existir
      azure_rm_virtualmachine:
        name: myUbuntuVM
        resource_group: myResourceGroup
        state: absent
      when: resource_group_check.resourcegroups | length > 0

    - name: Remover a interface de rede se existir
      azure_rm_networkinterface:
        name: myNIC
        resource_group: myResourceGroup
        state: absent
      when: resource_group_check.resourcegroups | length > 0

    - name: Remover o IP público se existir
      azure_rm_publicipaddress:
        name: myPublicIP
        resource_group: myResourceGroup
        state: absent
      when: resource_group_check.resourcegroups | length > 0

    - name: Remover a sub-rede se existir
      azure_rm_subnet:
        name: mySubnet
        resource_group: myResourceGroup
        virtual_network_name: myVnet
        state: absent
      when: resource_group_check.resourcegroups | length > 0

    - name: Remover a rede virtual se existir
      azure_rm_virtualnetwork:
        name: myVnet
        resource_group: myResourceGroup
        state: absent
      when: resource_group_check.resourcegroups | length > 0

    - name: Remover o grupo de segurança de rede se existir
      azure_rm_securitygroup:
        name: myNetworkSecurityGroup
        purge_rules: true
        resource_group: myResourceGroup
        state: absent
      when: resource_group_check.resourcegroups | length > 0

    - name: Remover o grupo de recursos se existir
      azure_rm_resourcegroup:
        name: myResourceGroup
        state: absent
      when: resource_group_check.resourcegroups | length > 0