---
- name: Import PostgreSQL GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL

- name: Install PostgreSQL repository
  ansible.builtin.yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: Disable the default PostgreSQL module
  ansible.builtin.yum:
    name: postgresql
    state: absent

- name: Install PostgreSQL server
  ansible.builtin.yum:
    name: postgresql{{ postgresql_version }}-server
    state: present

- name: Initialize PostgreSQL database
  ansible.builtin.command:
    cmd: /usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb
    creates: /var/lib/pgsql/{{ postgresql_version }}/data/PG_VERSION

- name: Enable and start PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql-{{ postgresql_version }}
    state: started
    enabled: yes

- name: Configure PostgreSQL to listen on all interfaces
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/{{ postgresql_version }}/data/postgresql.conf
    regexp: '^#listen_addresses'
    line: "listen_addresses = '*'"

- name: Configure pg_hba.conf to allow connections
  ansible.builtin.lineinfile:
    path: /var/lib/pgsql/{{ postgresql_version }}/data/pg_hba.conf
    line: "host    all             all             0.0.0.0/0               md5"
    create: yes

- name: Reload PostgreSQL configuration
  ansible.builtin.systemd:
    name: postgresql-{{ postgresql_version }}
    state: reloaded

- name: Create PostgreSQL database
  ansible.builtin.shell: |
    /usr/pgsql-{{ postgresql_version }}/bin/psql -U postgres -c "CREATE DATABASE {{ db_name }};"
  become_user: postgres

- name: Create PostgreSQL user
  ansible.builtin.shell: |
    /usr/pgsql-{{ postgresql_version }}/bin/psql -U postgres -c "CREATE USER {{ db_user }} WITH PASSWORD '{{ db_password }}';"
  become_user: postgres

- name: Grant privileges to PostgreSQL user on the database
  ansible.builtin.shell: |
    /usr/pgsql-{{ postgresql_version }}/bin/psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE {{ db_name }} TO {{ db_user }};"
  become_user: postgres